Add column sort order for data table
Teradata/covalent pull request #1799
Opened 2020-09-04 23:33 UTC by aqupriyanka

## Description

Add column sort order for data table component
### What's included?

- Add column sort order for data table component

#### Test Steps

- [ ] `npm run serve`
- [ ] then go to components -> Data table
- [ ] check the example with Data table with column sort order

#### General Tests for Every PR

- [ ] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build:lib` still works.

##### Screenshots or link to StackBlitz/Plunker

2020-09-05 04:27 UTC, philgetz requested changes
Small css change

2020-09-05 04:27 UTC, philgetz commented on src/platform/core/data-table/data-table.component.html
> +          <span *ngIf="column.columnSortOrder" class="push-left-xs header-number-circle mat-caption sort-order-bgc">
Sort-order-bgc, push-left-xs and mat-caption should all be covered in the .header-number-circle class, also we should probably rename it to something like td-data-table-sort-badge or something of the "sort".

2020-09-06 04:44 UTC, philgetz requested changes
Final touch kind of changes!

2020-09-06 04:44 UTC, philgetz commented on src/platform/core/data-table/_data-table-theme.scss
> +      weight: 400;
Well "sorted" out! One minor thing here, we can also use the [td-font-weight function from the utilities](https://github.com/Teradata/covalent/blob/fce891282294eec843d40dea6615f623778d723d/src/platform/core/common/styles/_typography-functions.scss#L17) to avoid some hard coding.

2020-09-06 04:44 UTC, philgetz commented on src/platform/core/data-table/data-table.component.scss
>    letter-spacing: normal;
I believe we can get rid of this now.

2020-09-06 04:45 UTC, philgetz commented on src/platform/core/data-table/data-table.component.scss
>    letter-spacing: normal;
I am talking about letter-spacing here

2020-09-08 15:52 UTC, philgetz approved these changes
LGTM

2020-09-08 15:59 UTC, emoralesb05 requested changes

2020-09-08 15:59 UTC, emoralesb05 commented on src/theme.scss
> +@include td-data-table-theme($theme);
No need to include the theme separately.

2020-09-08 15:59 UTC, emoralesb05 commented on src/theme.scss
> +  @include td-data-table-theme($theme-dark);
Same comment as the previous one.

2020-09-08 18:03 UTC, emoralesb05 approved these changes

2020-09-08 18:14 UTC, merged