Feat/angular 10
Teradata/covalent pull request #1808
Opened 2020-09-17 22:49 UTC by thomaslennan

## Description

Upgrade to Angular 10 and address audit issues

### What's included?
- Updated Angular core and material to version 10
- Ran audit fix

#### Test Steps
- [ ] Avoid error trying to update webdriver by setting the following in your environment: export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD='true'
- [ ] `npm run serve`
- [ ] Verify demos still work as expected
- [ ] `npm run serve:prod`
- [ ] Verify demos still work as expected
- [ ] `npm run build:lib`
- [ ] Verify builds to completion

#### General Tests for Every PR

- [ ] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build:lib` still works.

##### Screenshots or link to StackBlitz/Plunker

2020-10-01 23:21 UTC, emoralesb05 requested changes
I see a lot of changes in the PR that are not pertinent to angular being upgraded.. whats the thought process for that?

2020-10-01 23:46 UTC, emoralesb05 requested changes

2020-10-01 23:46 UTC, emoralesb05 commented on package.json
>      "@ngx-translate/core": "12.0.0",
We should update the ngx-translate dependencies

https://github.com/ngx-translate/core/releases

2020-10-01 23:46 UTC, emoralesb05 commented on src/platform/code-editor/package.json
> +    "tslib": "^2.0.0"
Do we need to add this into every package?

`@angular/material` installs this as a dependency for us.. so not sure we need to do it.

but if we must, lets make it a placeholder so its updated on build and not hardcoded.

2020-10-01 23:46 UTC, emoralesb05 commented on src/platform/core/layout/layout-toggle.class.ts
> +@Directive()
Was this a compilation error even for a super class?

2020-10-01 23:46 UTC, emoralesb05 commented on src/platform/echarts/base/series/series.component.ts
> +export interface ITdSeries extends ITdAnimation {
Do generics fail now?

2020-10-23 12:17 UTC, Zwartpet commented
Any ETA on this?

2020-10-23 18:57 UTC, thomaslennan commented on src/platform/core/layout/layout-toggle.class.ts
> +@Directive()
Angular 10 introduces a new requirement to have decorators on these classes and complained when trying to assign to abstract classes. That's why I removed the generics. The generic aspect didn't seem to be actually in direct usage so I think it's OK to have removed it. It had a big downstream effect on a number of classes that used the base abstract classes, hence the large number of file changes in this PR.

2020-10-23 18:57 UTC, thomaslennan commented on src/platform/code-editor/package.json
> +    "tslib": "^2.0.0"
Removed the specific injection of this dependency.

2020-10-23 18:57 UTC, thomaslennan commented on package.json
>      "@ngx-translate/core": "12.0.0",
Done. Also upgraded the http loader.

2020-10-23 18:58 UTC, thomaslennan commented on src/platform/echarts/base/series/series.component.ts
> +export interface ITdSeries extends ITdAnimation {
Yes. See above. Specifically, usage on abstract base classes pertaining to directives, etc.

2020-11-10 16:17 UTC, emoralesb05 approved these changes

2020-11-10 16:18 UTC, merged

2020-11-10 18:26 UTC, craigsmitham commented
🎉