Feat/vac 442 youtube markdown embeds
Teradata/covalent pull request #1831
Opened 2021-02-04 20:52 UTC by blackmjck

## Description
Page help desperately wants for video capability, so now we can add YouTube embedded videos natively like so:
```![youtu.be/videoID]```

### What's included?
- Native iframe embeds added for youtube share links
- Ability to embed playlists as well as single videos

#### General Tests for Every PR

- [x] `npm run serve:prod` still works.
- [x] `npm run tslint` passes.
- [x] `npm run stylelint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build:lib` still works.

##### Screenshots or link to StackBlitz/Plunker
<img width="826" alt="Screen Shot 2021-02-04 at 2 34 06 PM" src="https://user-images.githubusercontent.com/3385635/106945656-14176e80-66f6-11eb-9580-1ac7e8108d8c.png">

2021-02-04 20:56 UTC, fs250044 commented
Should this be made more generic (e.g., `[video url]`) in order to more easily support other video types (Vimeo, custom MP4s, etc)?

2021-02-04 21:17 UTC, blackmjck commented
**Note:** had to remove the `webdriver-manager update` part of the post-install hook as it's throwing errors

2021-02-04 21:30 UTC, JulieMarie requested changes
Thank you for startling me awake when I went to the demo....not sure `autoplay` is the way to go!  :P

2021-02-04 21:30 UTC, JulieMarie commented on src/platform/markdown/markdown.component.ts
> +  }
Maybe a better spot for this is in `markdown-utils/markdown-utils.ts`?

2021-02-04 22:14 UTC, blackmjck commented on src/platform/markdown/markdown.component.ts
> +  }
Good thinking. Done

2021-02-05 00:20 UTC, JulieMarie approved these changes

2021-02-05 19:27 UTC, owilliams320 approved these changes
LGTM

2021-02-05 19:31 UTC, merged