BREAKING CHANGE:  deprecating old components
Teradata/covalent pull request #1872
Opened 2022-01-19 19:57 UTC by owilliams320

## Description
Removing the 3.x Deprecated components

### Documentation matrix of deprecated list
| Covalent Compent | NG Material Replacement |
| ----------- | ----------- |
| data table | https://material.angular.io/components/table/overview |
| expansion panels	| https://material.angular.io/components/expansion/overview |
| sidesheet content | https://material.angular.io/components/sidenav/overview |
| virtual scrolling | https://material.angular.io/cdk/scrolling/overview |
| stepper | https://material.angular.io/cdk/stepper/overview |
| loading	| https://material.angular.io/components/progress-spinner/overview |
| notifications | https://material.angular.io/components/badge/overview |
| paging | https://material.angular.io/components/paginator/overview |
| nav steps | https://material.angular.io/components/stepper/overview |
| chips autocomplete | https://material.angular.io/components/chips/overview |
| tab select | https://material.angular.io/components/tabs/overview |
| http service |	https://angular.io/api/common/http |
| http decorators | https://angular.io/api/common/http |
| Query service | https://material.angular.io/cdk/layout/overview |
| toggle directive | https://material.angular.io/cdk/layout/overview |

#### General Tests for Every PR

- [ ] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build:lib` still works.

2022-01-20 21:33 UTC, JulieMarie requested changes

2022-01-20 21:33 UTC, JulieMarie commented on src/app/content/layouts/nav-list/nav-list.component.ts
> +        <div  >
Pickiness....get rid of the extra spaces.

2022-01-20 21:33 UTC, JulieMarie commented on src/app/content/layouts/nav-view/nav-view.component.ts
> +      <div layout-gt-sm="row"  >
Extra spaces

2022-01-20 21:33 UTC, JulieMarie commented on src/app/content/layouts/manage-list/manage-list.component.ts
> +          <div layout-gt-sm="row"  >
Extra spaces

2022-01-20 21:33 UTC, JulieMarie commented on src/platform/flavored-markdown/flavored-markdown.component.ts
> +  // private _replaceTables(markdown: string): string {
Why all this commented out code?

2022-01-20 22:57 UTC, owilliams320 commented on src/app/content/layouts/manage-list/manage-list.component.ts
> +          <div layout-gt-sm="row"  >
doh

2022-01-20 23:02 UTC, owilliams320 commented on src/platform/flavored-markdown/flavored-markdown.component.ts
> +  // private _replaceTables(markdown: string): string {
ah good catch. it was replacing tables with the deprecated td data tables....will look into replacing this with mat table

2022-01-21 01:48 UTC, JulieMarie approved these changes
Looks good now!

2022-01-21 02:23 UTC, merged