Feat/upgrade ng 13
Teradata/covalent pull request #1880
Opened 2022-01-28 01:39 UTC by owilliams320

## Description
Upgrading Covalent and all sub packages to NG 9

### What's included?
- Upgraded codebase to use NG13 and NG13 Material
- All packages now compiled in IVY Format

#### Test Steps
- [ ] `npm run serve`
- [ ]  Check localhost doc app
- [ ] `npm run test`
- [ ]  `npm run build:lib`

#### General Tests for Every PR

- [ ] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build:lib` still works.

##### Screenshots or link to StackBlitz/Plunker

2022-02-01 09:15 UTC, richavyas commented on src/app/content/components/component-demos/file-upload/demos/file-upload-demo.component.html
> -<file-upload-demo-basic></file-upload-demo-basic>
why to keep an empty file?

2022-02-01 09:17 UTC, richavyas commented on src/app/content/echarts/echarts-demos/map/demos/map-demo-basic/map-demo-basic.component.ts
> -import * as echarts from 'echarts';
how will `echarts.registerMap('USA', usaJSON);` work with echarts import?

2022-02-01 09:24 UTC, richavyas commented on src/platform/echarts/base/utils/echarts.ts
> -import * as echarts from 'echarts/lib/echarts';
do we not need this for registering theme?

2022-02-01 09:25 UTC, richavyas requested changes
left some minor comments

2022-02-01 15:54 UTC, owilliams320 commented on src/app/content/echarts/echarts-demos/map/demos/map-demo-basic/map-demo-basic.component.ts
> -import * as echarts from 'echarts';
since echarts is a commonJS dependency it should be imported via the "scripts" section in the consuming app's `angular.json` file.

The consuming app should also add the echart typings if they want to access methods like that

2022-02-01 15:55 UTC, owilliams320 commented on src/platform/echarts/base/utils/echarts.ts
> -import * as echarts from 'echarts/lib/echarts';
same comment as above. importing like this should be done in the scripts sections and methods accessed through the typings

2022-02-01 16:56 UTC, austinsley commented on scripts/build-release
> +#gulp compile-core-sass
Just curious... why comment this and L12 out?

2022-02-01 23:41 UTC, owilliams320 commented on scripts/build-release
> +#gulp compile-core-sass
Good catch!  only commented this to get the build running but fixed the underlying issue

2022-02-03 07:07 UTC, richavyas approved these changes
lgtm

2022-02-03 18:55 UTC, merged

2022-03-04 00:27 UTC, owilliams320 commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on:
- `v4.1.0`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-17 22:33 UTC, owilliams320 commented
:tada: This PR is included in version 4.1.0-develop.1 :tada:

The release is available on:
- `v4.1.0-develop.1`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v4.1.0-develop.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: