perf(markdown): do not run change detection when the markdown is clicked
Teradata/covalent pull request #1881
Opened 2022-02-01 06:29 UTC by arturovt

#### General Tests for Every PR

- [x] `npm run serve:prod` still works.
- [x] `npm run tslint` passes.
- [x] `npm run stylelint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build:lib` still works.

2022-02-03 18:51 UTC, owilliams320 commented
@arturovt looks like the tests are not passing

2022-02-03 18:54 UTC, owilliams320 requested changes

2022-02-03 18:54 UTC, owilliams320 commented on src/platform/markdown/markdown.component.ts
> +    this._removeClickListenerFn?.();
can we just name this something like `anchorListener`

2022-02-04 00:42 UTC, arturovt commented
@owilliams320 had to run run prettier locally since the lint job was failing.

2022-02-04 00:59 UTC, owilliams320 approved these changes
LGTM 🚀

2022-02-04 01:00 UTC, merged

2022-03-04 00:26 UTC, owilliams320 commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on:
- `v4.1.0`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-17 22:33 UTC, owilliams320 commented
:tada: This PR is included in version 4.1.0-develop.1 :tada:

The release is available on:
- `v4.1.0-develop.1`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v4.1.0-develop.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: