fix(markdown-flavored): teardown subscription when the view is destroyed
Teradata/covalent pull request #1924
Opened 2022-04-11 17:46 UTC by arturovt

2022-04-11 19:04 UTC, owilliams320 commented
the initial change looks good pls just rebase this branch w/ latest from main

2022-04-11 19:36 UTC, arturovt commented
Done. I've only noticed that you removed develop branch but kept pushing to develop.

2022-05-17 22:26 UTC, owilliams320 requested changes

2022-05-17 22:26 UTC, owilliams320 commented on libs/markdown-flavored/src/lib/flavored-markdown.component.ts
> +    this.clicked.complete();
not sure i 100% support this change. unless clicked event emitter is explicitly called here it's not necessary to call complete on destroy. In my opinion, if a consumer directly subscribed to this event emitter as opposed to using with angulars output templating then it should directly unsubscribe in the parent component

2022-05-18 10:48 UTC, arturovt commented on libs/markdown-flavored/src/lib/flavored-markdown.component.ts
> +    this.clicked.complete();
Well, I intentionally made this change since unsubscrubing in the parent component becomes a bit complicated. Well, we can add `takeUntil` to `clicked` before subscribing within the `_replaceButtons` method. What happens if the `TdFlavoredMarkdownButtonComponent` is destroyed before the parent component is destroyed? The subscribtion would exist until the parent component is destroyed. That's why I thought to call `.complete()` on the subject and added comments there since the parent and the child have different life spans.

2022-05-19 19:34 UTC, owilliams320 commented on libs/markdown-flavored/src/lib/flavored-markdown.component.ts
> +    this.clicked.complete();
would prefer to use takeUntil where it subscribes below.

2022-07-25 19:31 UTC, arturovt commented on libs/markdown-flavored/src/lib/flavored-markdown.component.ts
> +    this.clicked.complete();
@owilliams320 hey, updated, added takeUntil to where it subscribes.

2022-09-21 21:13 UTC, owilliams320 approved these changes
LGTM

2022-09-21 21:13 UTC, merged

2022-09-21 21:24 UTC, owilliams320 commented
:tada: This PR is included in version 4.6.1 :tada:

The release is available on:
- `v4.6.1`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v4.6.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: