perf(code-editor): do not run change detection whenever the editor does re-layout
Teradata/covalent pull request #1929
Opened 2022-04-11 21:12 UTC by arturovt

2022-05-12 13:21 UTC, owilliams320 requested changes

2022-05-12 13:21 UTC, owilliams320 commented on libs/angular-code-editor/src/lib/code-editor.component.ts
> +    this._ngZone.runOutsideAngular(() =>
not sure this really needs to be run outside of the ngzone? not seeing what would trigger change detection if its just getting values and triggering next in a behavior subject

2022-05-12 14:08 UTC, arturovt commented on libs/angular-code-editor/src/lib/code-editor.component.ts
> +    this._ngZone.runOutsideAngular(() =>
There's _timer_ (that acts as a setInterval) that triggers change detection

2022-07-25 19:26 UTC, arturovt commented
@owilliams320 friendly ping

2022-07-26 20:53 UTC, owilliams320 approved these changes

2022-07-26 20:54 UTC, merged

2022-07-26 21:02 UTC, owilliams320 commented
:tada: This PR is included in version 4.2.1 :tada:

The release is available on:
- `v4.2.1`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v4.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: