fix:minimize-help-code(vac-1333)
Teradata/covalent pull request #1937
Opened 2022-05-13 23:13 UTC by Msubhashini1

## Description

### What's included?

- One
- Two
- Three

#### Test Steps

- [ ] `npm run start`
- [ ] then this
- [ ] finally this

#### General Tests for Every PR

- [ ] `npm run start` still works.
- [ ] `npm run lint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build` still works.

##### Screenshots or link to StackBlitz/Plunker

2022-05-16 14:36 UTC, owilliams320 commented
Can you include a description of what is changing here and test steps? also a screen shot

2022-05-16 20:34 UTC, Msubhashini1 commented
>

2022-05-16 20:52 UTC, Msubhashini1 commented
> Can you include a description of what is changing here and test steps? also a screen shot

**Description** : Implemented minimized mode for the help component.
Test Steps: 1. Log in into the console app.
                     2. From left menu click on help icon, (i.e) last Icon  from bottom.
                     3. Help window will be open.
                     4. Inside window there will be maximized icon.
                     5. After we clicking on the maximized icon windo
<img width="762" alt="Minimized 2022-05-16 at 1 50 20 PM" src="https://user-images.githubusercontent.com/99816895/168680459-6d771524-6d82-43dc-a772-52c735c4086e.png">
w will be minimized and the icon will be changed to maximized. (vice versa will happen)

<img width="658" alt="Maximized 2022-05-16 at 1 50 34 PM" src="https://user-images.githubusercontent.com/99816895/168680609-4fdc290b-0bd4-47d0-830a-15d3676054b6.png">

2022-05-18 20:38 UTC, owilliams320 requested changes
looks good for the most part but looks like you still need to adjust the positioning when the help menu is minimized

<img width="487" alt="Screen Shot 2022-05-18 at 4 36 40 PM" src="https://user-images.githubusercontent.com/3837706/169151308-a8c08fc6-6169-4b3a-9340-d07e48a7a08d.png">

### Correct Spec
<img width="549" alt="Screen Shot 2022-05-18 at 4 38 00 PM" src="https://user-images.githubusercontent.com/3837706/169151514-b64d14e7-9db9-4ba9-aaf2-73300cc411f3.png">

2022-05-23 15:58 UTC, adamnel commented
There should be no gap between the icon buttons (the close icon and the dock icon). Right now looks like the markup has a space/line return in it which is separating them more than they should be.

Also, please verify in dark theme if you haven't already.

2022-05-23 21:23 UTC, Msubhashini1 commented
> looks good for the most part but looks like you still need to adjust the positioning when the help menu is minimized
> 
> <img alt="Screen Shot 2022-05-18 at 4 36 40 PM" width="487" src="https://user-images.githubusercontent.com/3837706/169151308-a8c08fc6-6169-4b3a-9340-d07e48a7a08d.png">
> 
> ### Correct Spec
> <img alt="Screen Shot 2022-05-18 at 4 38 00 PM" width="549" src="https://user-images.githubusercontent.com/3837706/169151514-b64d14e7-9db9-4ba9-aaf2-73300cc411f3.png">

@owilliams320 As per comments adjusted the positioning of the help menu.


<img width="663" alt="Minimized 2022-05-23 at 2 20 32 PM" src="https://user-images.githubusercontent.com/99816895/169908099-4a4330a3-5ca5-426e-9975-867455e71eb2.png">

2022-05-23 21:26 UTC, Msubhashini1 commented
> There should be no gap between the icon buttons (the close icon and the dock icon). Right now looks like the markup has a space/line return in it which is separating them more than they should be.
> 
> Also, please verify in dark theme if you haven't already.

@adamnel Removed space between the Icons of closed and minimized.
<img width="535" alt="Screen Shot 2022-05-23 at 2 20 03 PM" src="https://user-images.githubusercontent.com/99816895/169908456-c1055254-3bc2-41e8-956d-19970d982395.png">
<img width="510" alt="Screen Shot 2022-05-23 at 2 20 20 PM" src="https://user-images.githubusercontent.com/99816895/169908486-b89ab672-4616-4467-b830-dfbc5fcd660e.png">

2022-05-23 21:31 UTC, owilliams320 requested changes

2022-05-23 21:31 UTC, owilliams320 commented on libs/markdown-navigator/src/markdown-navigator-window-service/markdown-navigator-window.service.ts
> +const DEFAULT_POSITION: DialogPosition = { bottom: '0px', right: '10px' };
this should be 16px

2022-05-24 20:38 UTC, Msubhashini1 commented on libs/markdown-navigator/src/markdown-navigator-window-service/markdown-navigator-window.service.ts
> +const DEFAULT_POSITION: DialogPosition = { bottom: '0px', right: '10px' };
changed the pixel  to 16 px
<img width="479" alt="Screen Shot 2022-05-24 at 1 33 27 PM" src="https://user-images.githubusercontent.com/99816895/170127725-0cb4fd0e-0c53-4bd4-88e7-18122175562d.png">
<img width="507" alt="Screen Shot 2022-05-24 at 1 33 39 PM" src="https://user-images.githubusercontent.com/99816895/170127750-c162db41-b844-4e2c-9c65-e2439fd3c7f3.png">

2022-05-24 21:14 UTC, adamnel commented
For the minimized state:

![image](https://user-images.githubusercontent.com/1143267/170133478-b3b1db51-b3fd-4a2a-9752-3da51dd8e606.png)

Please remove the border radius along the bottom two corners

2022-05-26 19:48 UTC, Msubhashini1 commented
> For the minimized state:
> 
> ![image](https://user-images.githubusercontent.com/1143267/170133478-b3b1db51-b3fd-4a2a-9752-3da51dd8e606.png)
> 
> Please remove the border radius along the bottom two corners
<img width="680" alt="Screen Shot 2022-05-26 at 12 46 51 PM" src="https://user-images.githubusercontent.com/99816895/170565777-d8e449cc-0f90-4f0d-b18a-96a7158f67dc.png">

2022-05-26 19:57 UTC, adamnel commented
Close, but this removed the radius from the top corners as well and we still want those. Here's a mock

![image](https://user-images.githubusercontent.com/1143267/170567351-f77553ca-b747-49ee-8e3f-39dce68036ec.png)

2022-05-26 20:38 UTC, Msubhashini1 commented
> Close, but this removed the radius from the top corners as well and we still want those. Here's a mock
> 
<img width="664" alt="Screen Shot 2022-05-26 at 1 37 30 PM" src="https://user-images.githubusercontent.com/99816895/170576047-0494d246-da0c-4b6a-bd65-7c28bb49f24a.png">

> ![image](https://user-images.githubusercontent.com/1143267/170567351-f77553ca-b747-49ee-8e3f-39dce68036ec.png)

2022-07-21 14:01 UTC, closed without merging