fix(nx): side sheet behavior change
Teradata/covalent pull request #1972
Opened 2022-09-28 16:13 UTC by sailajanunna22

## Description

When secondary side sheet is opened, provide 3 options to user:

1. 'pushed'. --  push the parent side sheet to entire width of the window
2. 'shifted' -- shift the parent side sheet to left 
3. 'none' --  secondary sheet simply cover the parent

### What's included?

Secondary side sheet change

#### Test Steps

- [ ] `npm run start`
- [ ] then this
- [ ] finally this

#### General Tests for Every PR

- [ ] `npm run start` still works.
- [ ] `npm run lint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build` still works.

##### Screenshots or link to StackBlitz/Plunker
![Secondary sidesheet](https://user-images.githubusercontent.com/114519302/192831409-317c8eb4-44c4-41d9-900b-daac8ce8c333.gif)

2022-09-28 16:19 UTC, owilliams320 commented on apps/docs-app/src/app/content/components/component-demos/side-sheet/demos/side-sheet-demo-multi/side-sheet-demo-multi.component.ts
> +  openSideSheet(mode?: string): void {
This can just be written as `(mode: SubPageMode = SubPageMode.pushed)`

2022-09-28 16:46 UTC, owilliams320 requested changes
just had one comment

2022-09-28 18:03 UTC, sailajanunna22 commented on apps/docs-app/src/app/content/components/component-demos/side-sheet/demos/side-sheet-demo-multi/side-sheet-demo-multi.component.ts
> +  openSideSheet(mode?: string): void {
Fixed. Thanks

2022-09-29 14:14 UTC, owilliams320 approved these changes
LGTM

2022-09-29 14:14 UTC, merged

2022-09-29 14:22 UTC, owilliams320 commented
:tada: This PR is included in version 4.7.1 :tada:

The release is available on:
- `v4.7.1`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v4.7.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: