feat: add color use guide to covalent
Teradata/covalent pull request #1974
Opened 2022-09-28 18:54 UTC by ecni19

## Description

### Color use guide

Implemented [this Figma documentation](https://www.figma.com/file/7pzxuLUaKxE4A4uIPB8YUd/Color-use?node-id=337%3A2188) into Storybook.

### What's included?

* --mdc-theme-surface-emphasis, --mdc-theme-surface-emphasis-highlight, and --mdc-theme-surface-emphasis-highlight-hover have been added.
* --mdc-theme-surface-accent, --mdc-theme-surface-accent-highlight, and --mdc-theme-surface-accent-highlight-hover have also been added but they are just aliases for --mdc-theme-surface-primary, --mdc-theme-surface-primary-highlight, and --mdc-theme-surface-primary-highlight-hover.
* Some color values and opacities on the guide were changed to match what the variables actually are.
* App bar background color was removed.
* Card background color was updated to surface.

#### Test Steps

- [ ] `npm run storybook`
- [ ] Navigate to "Color use" under "Guides"
- [ ] Compare the story with this [Figma](https://www.figma.com/file/7pzxuLUaKxE4A4uIPB8YUd/Color-use?node-id=337%3A2188)

#### General Tests for Every PR

- [ ] `npm run start` still works.
- [ ] `npm run lint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build` still works.

Receiving this error when I run any of these commands:

```
 >  NX   Unhandled error in task executor

TypeError: Cannot read properties of undefined (reading 'tasks')
    at calculateReverseDeps (/Users/eric.ni/node_modules/nx/src/tasks-runner/utils.js:160:27)
    at new TasksSchedule (/Users/eric.ni/node_modules/nx/src/tasks-runner/tasks-schedule.js:16:65)
    at new TaskOrchestrator (/Users/eric.ni/node_modules/nx/src/tasks-runner/task-orchestrator.js:26:30)
    at /Users/eric.ni/node_modules/nx/src/tasks-runner/default-tasks-runner.js:33:30
    at Generator.next (<anonymous>)
    at /Users/eric.ni/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/eric.ni/node_modules/tslib/tslib.js:114:16)
    at runAllTasks (/Users/eric.ni/node_modules/nx/src/tasks-runner/default-tasks-runner.js:28:20)
    at /Users/eric.ni/node_modules/nx/src/tasks-runner/default-tasks-runner.js:19:22
```

![ColorUse](https://user-images.githubusercontent.com/47995084/192865231-2d2ebc4f-bbff-4db7-b8de-c731bad9ec9a.gif)

2022-09-28 21:18 UTC, adamnel submitted a review, later dismissed

2022-09-29 13:54 UTC, mikespudwebb approved these changes

2022-09-29 14:18 UTC, owilliams320 requested changes
just have one comment

2022-09-29 14:18 UTC, owilliams320 commented on libs/components/styles/theme/_all-theme.scss
> +  // @include chips.chips-theme($theme);
can uncomment this ?

2022-09-29 15:59 UTC, ecni19 commented on libs/components/styles/theme/_all-theme.scss
> +  // @include chips.chips-theme($theme);
Done

2022-09-29 16:42 UTC, owilliams320 approved these changes

2022-09-29 16:42 UTC, merged

2022-09-29 16:50 UTC, owilliams320 commented
:tada: This PR is included in version 4.8.0 :tada:

The release is available on:
- `v4.8.0`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v4.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: