feat(components): expansion panel web component
Teradata/covalent pull request #2051
Opened 2023-08-30 18:19 UTC by carolineguzylak

## Description

Developed expansion panel component using Lit framework - implemented in storybook.

### What's included?

- Expansion panel component
- Expansion panel documentation page

#### Test Steps

- [ ] `npm run storybook`

#### General Tests for Every PR

- [ ] `npm run start` still works.
- [ ] `npm run lint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build` still works.

##### Screenshots or link to StackBlitz/Plunker

<img width="574" alt="Screenshot 2023-08-30 at 11 17 04 AM" src="https://github.com/Teradata/covalent/assets/74155787/9671cba7-06bb-402f-95fe-12af910b3222">
<img width="571" alt="Screenshot 2023-08-30 at 11 17 21 AM" src="https://github.com/Teradata/covalent/assets/74155787/848979ee-a68e-4f36-a472-ef2484336316">

2023-08-31 19:39 UTC, owilliams320 requested changes

2023-08-31 19:39 UTC, owilliams320 commented on libs/components/src/expansion-panel/cv-expansion-panel.ts
> +    if (open) {
does this do anything? looks like panel.open would already be true from above if the open variable is already assigned from panel.open?

2023-08-31 19:57 UTC, owilliams320 commented
@carolineguzylak looks like there is a few lint and build issues. You should be able to run locally using `nx affected build` and `nx affected lint`

2023-09-03 03:35 UTC, carolineguzylak commented on libs/components/src/expansion-panel/cv-expansion-panel.ts
> +    if (open) {
I removed this

2023-09-06 18:26 UTC, owilliams320 requested changes
One comment then looks good

2023-09-06 20:30 UTC, owilliams320 commented
@carolineguzylak looks like the pipeline did not pass you should be able run `npm run lint -- --fix`

2023-09-06 21:53 UTC, carolineguzylak commented on libs/components/src/expansion-panel/cv-expansion-panel-item.ts
> +import '../action-ribbon/action-ribbon';
Yes

2023-09-06 21:54 UTC, carolineguzylak commented
> @carolineguzylak looks like the pipeline did not pass you should be able run `npm run lint -- --fix`

2023-09-07 21:48 UTC, owilliams320 approved these changes
LGTM! 🏎️

2023-09-07 21:49 UTC, merged

2023-09-07 21:53 UTC, owilliams320 commented
:tada: This PR is included in version 7.1.0 :tada:

The release is available on:
- `v7.1.0`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v7.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: