feat(icon-button-toggle): create new web component icon-button-toggle
Teradata/covalent pull request #2135
Opened 2024-03-26 15:51 UTC by bsahitya

## Description

Created a new web component called `cv-icon-button-toggle`.
It extends the functionality from [`mwc-icon-button-toggle`](https://www.npmjs.com/package/@material/mwc-icon-button-toggle/v/0.24.0-canary.8dff8894.0)

### What's included?

Icon button toggle component which can be toggled on/off and disabled.
It has the below properties:
- aria-label: Accessible label for the button.
- on: To toggle the button on/off.
- onIcon: Icon to display when on is true.
- offIcon: Icon to display when on is false.
- disabled: To disable the button.
- ariaLabelOn: aria-label of the button when on is true. If set, ariaLabelOff must also be set.
- ariaLabelOff: aria-label of the button when on is false. If set, ariaLabelOn must also be set.

#### Test Steps

- [x] `npm run storybook`
- [x] Navigate to Icon Button Toggle component in the side nav
- [x] Test the component

#### General Tests for Every PR

- [x] `npm run start` still works.
- [x] `npm run lint` passes.
- [x] `npm run stylelint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

##### Screenshots
![icon-button-toggle](https://github.com/Teradata/covalent/assets/148156994/a42b9ecb-eab0-4690-8045-4f2a2fabc7ba)

2024-04-01 19:57 UTC, vicalcantFrontEnd commented on libs/components/src/icon-button-toggle/icon-button-toggle.scss
> +  color: var(--cv-theme-primary);
looks good!

2024-04-01 20:38 UTC, vicalcantFrontEnd approved these changes

2024-04-02 15:28 UTC, owilliams320 requested changes

2024-04-02 15:28 UTC, owilliams320 commented on libs/components/src/icon-button-toggle/icon-button-toggle.scss
> +  --mdc-ripple-color: var(--cv-theme-primary);
lets move this ripple color to only the "on" state as well.

2024-04-02 18:07 UTC, bsahitya commented on libs/components/src/icon-button-toggle/icon-button-toggle.scss
> +  --mdc-ripple-color: var(--cv-theme-primary);
Consulted Adam and made changes to have the default grey ripple in the off state.

2024-04-03 19:52 UTC, owilliams320 approved these changes

2024-04-03 19:53 UTC, merged

2024-04-03 19:59 UTC, owilliams320 commented
:tada: This PR is included in version 8.9.0 :tada:

The release is available on:
- `v8.9.0`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v8.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: