fix(app-shell): enhancement to be resizable app-shell
Teradata/covalent pull request #2152
Opened 2024-04-29 12:51 UTC by vicalcantFrontEnd

## Description

The help option panel is now resizable to the left, it can now scroll with a maximum width of 600 px. Help panel text wraps automatically

### What's included?

- This PR includes the functionality to make the Help Panel resizable

#### Test Steps

- [ ] `npm run start`
- [ ] then this
- [ ] finally this

#### General Tests for Every PR

- [ ] `npm run start` still works.
- [ ] `npm run lint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build` still works.

##### Screenshots or link to StackBlitz/Plunker

2024-04-29 13:32 UTC, adamnel requested changes
Looks very nice visually.  A couple functional tweaks:
- It's laggy, the mouse can move independently of the drag line and it takes a bit to catch up
- Probably related: the highlighted drag line doesn't stay highlighted while dragging if the mouse has moved off of it
- The panel resets to the default width every time it's closed. It should reopen to the previous width for some duration of time, probably just for the current session
- A double-click on the drag line should reset the width to the default starter width

![help-resize](https://github.com/Teradata/covalent/assets/1143267/b21b7d54-5299-4cdb-8dd4-09ea00115225)

2024-05-01 13:48 UTC, owilliams320 commented
@vicalcantFrontEnd In general this is looking good! i did notice the delay is from the transition-property...not sure how you want to handle this but looks like while we are resizing we want to disable the transition property, but have it enabled when the use clicks open/close action.

```
transition-property: width;
transition-duration: 200ms;
```

2024-05-01 13:57 UTC, owilliams320 requested changes
I also notice when in small view the help panel no longer takes up the full width of the screen. this is a regression and should be accounted for as well.

2024-05-07 05:15 UTC, vicalcantFrontEnd commented
> Looks very nice visually. A couple functional tweaks:
> 
> * It's laggy, the mouse can move independently of the drag line and it takes a bit to catch up
> * Probably related: the highlighted drag line doesn't stay highlighted while dragging if the mouse has moved off of it
> * The panel resets to the default width every time it's closed. It should reopen to the previous width for some duration of time, probably just for the current session
> * A double-click on the drag line should reset the width to the default starter width
> 
> ![help-resize](https://private-user-images.githubusercontent.com/1143267/326455779-b21b7d54-5299-4cdb-8dd4-09ea00115225.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTkwODAsIm5iZiI6MTcxNTA1ODc4MCwicGF0aCI6Ii8xMTQzMjY3LzMyNjQ1NTc3OS1iMjFiN2Q1NC01Mjk5LTRjZGItOGRkNC0wOWVhMDAxMTUyMjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDUxMzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZiOWE3MTZiNmE5MmY5YjU2ZDMzYzRjOTgxZTQ5ZDI2MjAyYTg0ZTNlNWQzOWQ5NTI2MDNkYzhlYTI2NmNmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AQotwMwAuZN9S3tI3Jzy2ApTFWaNlUpMkgRd5W2JUnM) [ ![help-resize](https://private-user-images.githubusercontent.com/1143267/326455779-b21b7d54-5299-4cdb-8dd4-09ea00115225.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTkwODAsIm5iZiI6MTcxNTA1ODc4MCwicGF0aCI6Ii8xMTQzMjY3LzMyNjQ1NTc3OS1iMjFiN2Q1NC01Mjk5LTRjZGItOGRkNC0wOWVhMDAxMTUyMjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDUxMzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZiOWE3MTZiNmE5MmY5YjU2ZDMzYzRjOTgxZTQ5ZDI2MjAyYTg0ZTNlNWQzOWQ5NTI2MDNkYzhlYTI2NmNmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AQotwMwAuZN9S3tI3Jzy2ApTFWaNlUpMkgRd5W2JUnM) ](https://private-user-images.githubusercontent.com/1143267/326455779-b21b7d54-5299-4cdb-8dd4-09ea00115225.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTkwODAsIm5iZiI6MTcxNTA1ODc4MCwicGF0aCI6Ii8xMTQzMjY3LzMyNjQ1NTc3OS1iMjFiN2Q1NC01Mjk5LTRjZGItOGRkNC0wOWVhMDAxMTUyMjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDUxMzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZiOWE3MTZiNmE5MmY5YjU2ZDMzYzRjOTgxZTQ5ZDI2MjAyYTg0ZTNlNWQzOWQ5NTI2MDNkYzhlYTI2NmNmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AQotwMwAuZN9S3tI3Jzy2ApTFWaNlUpMkgRd5W2JUnM) [ ](https://private-user-images.githubusercontent.com/1143267/326455779-b21b7d54-5299-4cdb-8dd4-09ea00115225.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTkwODAsIm5iZiI6MTcxNTA1ODc4MCwicGF0aCI6Ii8xMTQzMjY3LzMyNjQ1NTc3OS1iMjFiN2Q1NC01Mjk5LTRjZGItOGRkNC0wOWVhMDAxMTUyMjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDUxMzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZiOWE3MTZiNmE5MmY5YjU2ZDMzYzRjOTgxZTQ5ZDI2MjAyYTg0ZTNlNWQzOWQ5NTI2MDNkYzhlYTI2NmNmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AQotwMwAuZN9S3tI3Jzy2ApTFWaNlUpMkgRd5W2JUnM)

@adamnel  I push the version with the features that are in the comments, please let me know if you have some questions or changes.

![app-shell](https://github.com/Teradata/covalent/assets/73868044/8336bb81-57d6-4fe8-b376-28794899fb50)

2024-05-07 05:16 UTC, vicalcantFrontEnd commented
> I also notice when in small view the help panel no longer takes up the full width of the screen. this is a regression and should be accounted for as well.

Fixed the responsive mode 

![app-shell](https://github.com/Teradata/covalent/assets/73868044/238ec165-dbd0-48c7-9555-42a0a2c92003)

2024-05-07 13:20 UTC, adamnel requested changes
We don't want to limit the width of the help panel, or rather, any limitation should come from a minimum width or other control on the main content. 

Right now the help panel looks to be maxed out at 600px wide, but this forces it to be artificially narrow on wide screens, but still allows it to crush the content on narrower ones. That main content should handle its own min width to prevent the crushing, not the panel itself setting an arbitrary max value.

2024-05-08 13:16 UTC, vicalcantFrontEnd commented
> We don't want to limit the width of the help panel, or rather, any limitation should come from a minimum width or other control on the main content.
> 
> Right now the help panel looks to be maxed out at 600px wide, but this forces it to be artificially narrow on wide screens, but still allows it to crush the content on narrower ones. That main content should handle its own min width to prevent the crushing, not the panel itself setting an arbitrary max value.

Thank you for your comments. To make sure I'm understanding the proposed changes, I'd like to confirm a couple of points:

1. Remove the 600px width restriction to allow for greater flexibility on larger screens?
2. Add a min-width to the main content to ensure its usability and legibility under all conditions. What do you think would be an appropriate value in pixels for this min-width?
3. Behavior on Small Screens, currently, the help panel covers 100% of the width on small screens. Would you like to maintain this design, or is there any modification we should consider to improve the experience on small devices?

2024-05-08 13:57 UTC, adamnel commented
> 1. Remove the 600px width restriction to allow for greater flexibility on larger screens.

Correct

> 2. Add a min-width to the main content to ensure its usability and legibility under all conditions. What do you think would be an appropriate value in pixels for this min-width?

The main content to be able to override this value on any given screen but set a default of 600px.

> 3. Behavior on Small Screens, currently, the help panel covers 100% of the width on small screens. Would you like to maintain this design, or is there any modification we should consider to improve the experience on small devices?

The behavior on small screens is good as is.

2024-05-13 16:22 UTC, vicalcantFrontEnd commented
> > 1. Remove the 600px width restriction to allow for greater flexibility on larger screens.
> 
> Correct
> 
> > 2. Add a min-width to the main content to ensure its usability and legibility under all conditions. What do you think would be an appropriate value in pixels for this min-width?
> 
> The main content should be able to override this value on any given screen but set a default of 600px.
> 
> > 3. Behavior on Small Screens, currently, the help panel covers 100% of the width on small screens. Would you like to maintain this design, or is there any modification we should consider to improve the experience on small devices?
> 
> The behavior on small screens is good as is.

@adamnel I remove the max-width 600px restriction in the help pannel and add min-width to main  to ensure its its usability and legibility under all conditions.

2024-05-13 16:39 UTC, adamnel approved these changes
Looks great!

2024-05-13 17:51 UTC, bsahitya approved these changes
Looks great! 🎉

2024-05-13 18:27 UTC, owilliams320 approved these changes
🔥

2024-05-13 18:28 UTC, merged

2024-05-13 18:30 UTC, owilliams320 commented
:tada: This PR is included in version 8.12.1 :tada:

The release is available on:
- `v8.12.1`
- [GitHub release](https://github.com/Teradata/covalent/releases/tag/v8.12.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: