feat(components): add notebook, cell and code editor components
Teradata/covalent pull request #2209
Opened 2024-07-29 22:06 UTC by bsahitya

## Description

Web components added:
1. Code editor
2. Notebook
3. Notebook cell

### What's included?

1. Code editor - Creates a monaco editor instance with the options passed
2. Notebook - Resembles a python notebook. Takes notebook cells as children through a slot.
3. Notebook cell - Resembles a python notebook cell

#### Test Steps

- [x] `npm run storybook`
- [x] Navigate to Notebook, Notebook cell & Code editor components
- [x] Play around with the properties

#### General Tests for Every PR

- [x] `npm run start` still works.
- [x] `npm run lint` passes.
- [x] `npm run stylelint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

##### Screenshots or link to StackBlitz/Plunker
#### Code editor
<img width="821" alt="Screenshot 2024-07-29 at 5 03 33 PM" src="https://github.com/user-attachments/assets/2d645253-6a00-48ed-9d5b-7ef8c569a741">

#### Notebook cell
<img width="997" alt="Screenshot 2024-07-29 at 5 04 27 PM" src="https://github.com/user-attachments/assets/5370ef04-65a5-43be-a216-11d27cd3323e">

#### Notebook
<img width="1101" alt="Screenshot 2024-07-29 at 5 03 08 PM" src="https://github.com/user-attachments/assets/f319b20f-4b1f-4b2e-9e2c-d13db7eea0f8">

2024-07-30 14:24 UTC, owilliams320 requested changes
Just had a few comments

2024-07-30 14:24 UTC, owilliams320 commented on libs/components/src/code-editor/code-editor.scss
> +:host {
Can we prefix these variables with `cv`

2024-07-30 14:24 UTC, owilliams320 commented on libs/components/src/notebook-cell/notebook-cell.ts
> +    const output = html` <div class="errors"><slot name="error"></slot></div>
can we use the page level alerts component for errors? https://teradata.github.io/covalent/docs/components/?path=/story/components-alert--page-level&args=state:negative

2024-07-31 14:21 UTC, owilliams320 approved these changes

2024-08-05 18:08 UTC, bsahitya commented on libs/components/src/notebook/notebook.ts
> +          label="Cell type"
Added an input called `labels` for the labels and tooltips to be passed from the consumer.

2024-08-07 16:21 UTC, closed without merging